'use client'

import { useState } from 'react'

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const TIMEZONES = [
  { label: 'India (IST)', value: 'Asia/Kolkata' },
  { label: 'Singapore (SGT)', value: 'Asia/Singapore' },
  { label: 'UAE (GST)', value: 'Asia/Dubai' },
  { label: 'UK (GMT)', value: 'Europe/London' },
  { label: 'US East (EST)', value: 'America/New_York' },
  { label: 'US West (PST)', value: 'America/Los_Angeles' },
  { label: 'Australia (AEST)', value: 'Australia/Sydney' },
]
const FREQUENCIES = ['Every week', 'Every 2 weeks', 'Every month']
const TIMES = ['7:00 AM', '8:00 AM', '9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '6:00 PM', '7:00 PM', '8:00 PM']
interface Props { userEmail: string }

export default function PromptsView({ userEmail }: Props) {
  const [activeTab, setActiveTab] = useState<'next' | 'schedule' | 'history'>('next')
  const [selectedDay, setSelectedDay] = useState('Sun')
  const [selectedTime, setSelectedTime] = useState('9:00 AM')
  const [selectedFreq, setSelectedFreq] = useState('Every week')
  const [selectedTz, setSelectedTz] = useState('Asia/Kolkata')
  const [promptText, setPromptText] = useState('What is your favourite memory of the monsoon season? A moment, a smell, a feeling — anything that comes to mind.')
  const [editing, setEditing] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [saved, setSaved] = useState(false)
  const [sending, setSending] = useState(false)
  const [sendStatus, setSendStatus] = useState<'success' | 'error' | null>(null)

  async function handleGenerate() {
    setGenerating(true)
    setTimeout(() => {
      const prompts = [
        'What did your childhood home look like? Can you describe it in detail — the rooms, the smells, the sounds?',
        'Tell me about the moment you knew you wanted to marry your partner. What happened?',
        'What was the hardest period of your life, and what got you through it?',
        'What is a recipe you know by heart that you learned from your mother?',
        'What advice would you give to your younger self?',
        'Tell me about a teacher or mentor who changed your life.',
        'What is something you sacrificed for your children that you never told them about?',
      ]
      setPromptText(prompts[Math.floor(Math.random() * prompts.length)])
      setGenerating(false)
    }, 1200)
  }

  async function handleSendPrompt() {
    setSending(true)
    try {
      const res = await fetch('/api/send-prompt', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: promptText,
          userEmail,
        }),
      })

      const data = await res.json()

      if (data.success) {
        setSendStatus('success')
      } else {
        setSendStatus('error')
      }
    } catch {
      setSendStatus('error')
    } finally {
      setSending(false)
      setTimeout(() => setSendStatus(null), 3000) // auto-hide
    }
  }

  function handleSaveSchedule() {
    setSaved(true)
    setTimeout(() => setSaved(false), 2000)
  }

  const inputStyle = { fontSize: '13px', color: '#1C1917', background: '#FDF8F3', border: '0.5px solid #E8E0D5', borderRadius: '8px', padding: '8px 12px', width: '100%', outline: 'none' } as React.CSSProperties

  return (
    <div>
      {/* Tabs */}
      <div style={{ display: 'flex', gap: '0', marginBottom: '24px', borderBottom: '0.5px solid #E8E0D5' }}>
        {(['next', 'schedule', 'history'] as const).map(tab => (
          <button key={tab} onClick={() => setActiveTab(tab)} style={{ padding: '8px 16px', fontSize: '13px', color: activeTab === tab ? '#1C1917' : '#78716C', cursor: 'pointer', background: 'none', border: 'none', borderBottom: activeTab === tab ? '2px solid #1C1917' : '2px solid transparent', fontWeight: activeTab === tab ? 500 : 400, marginBottom: '-0.5px' }}>
            {tab === 'next' ? 'Next prompt' : tab === 'schedule' ? 'Schedule' : 'History'}
          </button>
        ))}
      </div>

      {/* Next prompt tab */}
      {activeTab === 'next' && (
        <div>
          <div style={{ background: 'white', border: '0.5px solid #E8E0D5', borderRadius: '16px', padding: '24px', marginBottom: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
              <div>
                <p style={{ fontSize: '11px', fontWeight: 500, color: '#A8A29E', textTransform: 'uppercase', letterSpacing: '0.06em', margin: '0 0 4px' }}>
                  Sending this {selectedDay === 'Sun' ? 'Sunday' : selectedDay} · {selectedTime} IST
                </p>
                <p style={{ fontSize: '13px', color: '#78716C', margin: 0 }}>Generated by Rooh · edit or regenerate below</p>
              </div>
              <span style={{ fontSize: '11px', fontWeight: 500, padding: '3px 10px', borderRadius: '20px', background: '#EEEDFE', color: '#3C3489' }}>Childhood</span>
            </div>

            {editing ? (
              <textarea
                value={promptText}
                onChange={e => setPromptText(e.target.value)}
                style={{ ...inputStyle, width: '100%', minHeight: '100px', resize: 'vertical', fontFamily: 'Georgia, serif', fontSize: '15px', lineHeight: 1.6, marginBottom: '16px', boxSizing: 'border-box', borderLeft: '3px solid #1D9E75' }}
              />
            ) : (
              <div style={{ fontFamily: 'Georgia, serif', fontSize: '16px', color: '#1C1917', lineHeight: 1.6, marginBottom: '16px', padding: '14px 16px', background: '#FDF8F3', borderRadius: '10px', borderLeft: '3px solid #1D9E75', cursor: 'text' }} onClick={() => setEditing(true)}>
                "{promptText}"
              </div>
            )}

            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
              <button onClick={editing ? () => setEditing(false) : handleSendPrompt} style={{
    padding: '8px 18px',
    background: '#1C1917',
    color: '#FDF8F3',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 500,
    cursor: sending ? 'not-allowed' : 'pointer',
    opacity: sending ? 0.6 : 1
  }}>
                {sending ? 'Sending...' : editing ? 'Save prompt' : 'Send as is ✓'}
              </button>
              {!editing && <button onClick={() => setEditing(true)} style={{ padding: '8px 18px', background: 'white', color: '#1C1917', border: '0.5px solid #E8E0D5', borderRadius: '8px', fontSize: '13px', cursor: 'pointer' }}>Edit</button>}
              <button onClick={handleGenerate} disabled={generating} style={{ padding: '8px 18px', background: 'transparent', color: '#78716C', border: '0.5px solid #E8E0D5', borderRadius: '8px', fontSize: '13px', cursor: 'pointer', opacity: generating ? 0.6 : 1 }}>
                {generating ? 'Generating...' : 'Generate new ↻'}
              </button>
            </div>
          </div>

          {/* ✅ Feedback UI */}
          {sendStatus === 'success' && (
            <div style={{
              background: '#F0FAF6',
              border: '0.5px solid #9FE1CB',
              borderRadius: '12px',
              padding: '12px 16px',
              marginBottom: '12px'
            }}>
              <p style={{ fontSize: '13px', color: '#085041', margin: 0 }}>
                Prompt sent successfully ✓
              </p>
            </div>
          )}

          {sendStatus === 'error' && (
            <div style={{
              background: '#FEF2F2',
              border: '0.5px solid #FECACA',
              borderRadius: '12px',
              padding: '12px 16px',
              marginBottom: '12px'
            }}>
              <p style={{ fontSize: '13px', color: '#7F1D1D', margin: 0 }}>
                Failed to send prompt. Please try again.
              </p>
            </div>
          )}

          <div style={{ background: '#F0FAF6', border: '0.5px solid #9FE1CB', borderRadius: '12px', padding: '14px 16px' }}>
            <p style={{ fontSize: '13px', color: '#085041', margin: 0 }}>
              This prompt will be sent to your parent on WhatsApp. They just need to press and hold the microphone button to reply.
            </p>
          </div>
        </div>
      )}

      {/* Schedule tab */}
      {activeTab === 'schedule' && (
        <div style={{ background: 'white', border: '0.5px solid #E8E0D5', borderRadius: '16px', padding: '24px' }}>
          <div style={{ marginBottom: '20px' }}>
            <p style={{ fontSize: '13px', color: '#78716C', marginBottom: '10px' }}>Send on</p>
            <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
              {DAYS.map(day => (
                <button key={day} onClick={() => setSelectedDay(day)} style={{ padding: '6px 12px', borderRadius: '20px', fontSize: '13px', border: selectedDay === day ? '1px solid #1C1917' : '0.5px solid #E8E0D5', background: selectedDay === day ? '#1C1917' : 'white', color: selectedDay === day ? '#FDF8F3' : '#78716C', cursor: 'pointer' }}>
                  {day}
                </button>
              ))}
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '20px' }}>
            <div>
              <p style={{ fontSize: '13px', color: '#78716C', marginBottom: '8px' }}>Time (parent's local time)</p>
              <select value={selectedTime} onChange={e => setSelectedTime(e.target.value)} style={inputStyle}>
                {TIMES.map(t => <option key={t}>{t}</option>)}
              </select>
            </div>
            <div>
              <p style={{ fontSize: '13px', color: '#78716C', marginBottom: '8px' }}>Frequency</p>
              <select value={selectedFreq} onChange={e => setSelectedFreq(e.target.value)} style={inputStyle}>
                {FREQUENCIES.map(f => <option key={f}>{f}</option>)}
              </select>
            </div>
          </div>

          <div style={{ marginBottom: '24px' }}>
            <p style={{ fontSize: '13px', color: '#78716C', marginBottom: '8px' }}>Parent's timezone</p>
            <select value={selectedTz} onChange={e => setSelectedTz(e.target.value)} style={inputStyle}>
              {TIMEZONES.map(tz => <option key={tz.value} value={tz.value}>{tz.label}</option>)}
            </select>
          </div>

          <button onClick={handleSaveSchedule} style={{ padding: '10px 20px', background: '#1C1917', color: '#FDF8F3', border: 'none', borderRadius: '8px', fontSize: '14px', fontWeight: 500, cursor: 'pointer' }}>
            {saved ? 'Saved ✓' : 'Save schedule'}
          </button>
        </div>
      )}

      {/* History tab */}
      {activeTab === 'history' && (
        <div style={{ background: 'white', border: '0.5px solid #E8E0D5', borderRadius: '16px', overflow: 'hidden' }}>
          {[
            { date: '30 Mar', prompt: 'Tell me about a festival memory from your childhood.', responded: true },
            { date: '23 Mar', prompt: 'What was your favourite subject in school and why?', responded: true },
            { date: '16 Mar', prompt: 'Describe the neighbourhood where you grew up.', responded: false },
            { date: '9 Mar', prompt: 'What is a piece of advice your parents gave you that stayed with you?', responded: true },
          ].map((item, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '16px', padding: '14px 20px', borderBottom: i < 3 ? '0.5px solid #F5F0EA' : 'none' }}>
              <span style={{ fontSize: '12px', color: '#A8A29E', flexShrink: 0, width: '50px', paddingTop: '2px' }}>{item.date}</span>
              <p style={{ fontSize: '13px', color: '#57534E', flex: 1, margin: 0, lineHeight: 1.5 }}>"{item.prompt}"</p>
              <span style={{ fontSize: '11px', padding: '2px 8px', borderRadius: '20px', flexShrink: 0, background: item.responded ? '#E1F5EE' : '#F1EFE8', color: item.responded ? '#085041' : '#444441' }}>
                {item.responded ? 'Responded' : 'No response'}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
